/**
 * This code was generated by Builder.io.
 */
import * as React from 'react';

export default async function Page() {
  return (
    <>
      <div className="box-border flex min-h-[100px] shrink-0 flex-col px-5 pb-12 pt-8 text-white max-sm:pb-10">
        <section className="mx-auto box-border flex min-h-[100px] w-full max-w-[1200px] shrink-0 grow flex-col self-stretch px-5 pb-12 pt-8 text-white max-sm:pb-10">
          <img
            loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2Ff7bea1b7734840ffb6a2d2b603acb307%2F157c4719fb274b3ba9f396de13c0b3c6"
            className="mx-auto mt-5 box-border aspect-[1.53] min-h-[20px] w-full min-w-[20px] max-w-[500px] shrink-0 overflow-hidden bg-cover bg-center bg-no-repeat object-cover"
          />
          <div
            className="relative box-border flex min-h-0 shrink-0 flex-col self-stretch bg-cover bg-center bg-no-repeat px-6 pb-6 pt-5 max-md:h-auto max-md:grow-0 max-sm:ml-[calc(50%_-_50vw)] max-sm:h-screen max-sm:w-screen"
            style={{ maxWidth: 1200 }}
          >
            <section className="relative mx-auto box-border flex min-h-0 w-full max-w-[1200px] shrink-0 grow flex-col self-stretch bg-cover bg-center bg-no-repeat px-6 pb-6 pt-5 max-md:h-auto max-md:grow-0 max-sm:ml-[calc(50%_-_50vw)] max-sm:h-screen max-sm:w-screen">
              <div className="mt-2 max-w-full self-center text-left text-2xl font-light tracking-normal text-orange-400 max-md:text-center max-sm:text-base max-sm:tracking-wider">
                <p>Une application pour vous</p>
              </div>
              <div className="max-w-full self-center text-left text-5xl font-bold leading-[57.6px] tracking-tight text-orange-400 max-md:w-auto max-md:self-stretch max-md:text-center max-md:text-5xl max-sm:text-4xl">
                <p>faciliter la vie associative</p>
              </div>
              <div className="mr-auto mt-9 flex w-full flex-row justify-center gap-4 self-center max-md:mx-auto max-md:w-full max-md:max-w-[520px] max-md:items-center max-md:justify-center max-md:self-stretch">
                <a
                  href="https://wasso.flutterflow.app/"
                  className="flex w-auto flex-row flex-wrap justify-center self-center rounded-lg max-md:mt-[px] max-md:flex max-md:flex-row max-md:flex-wrap max-md:justify-between"
                >
                  <div className="w-auto items-center justify-center self-stretch rounded-[38px] bg-orange-400 px-5 py-4 text-center text-lg leading-6 text-white max-md:w-full max-md:max-w-[500px] max-sm:m-auto max-sm:h-auto max-sm:py-3">
                    <p>Je crée mon compte gratuit en 2 min</p>
                  </div>
                </a>
              </div>
              <div className="relative my-auto box-border flex w-full max-w-[1440px] shrink-0 flex-col self-stretch max-md:mt-12 max-md:h-auto max-md:grow max-sm:m-auto">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                  <div className="flex w-full flex-col max-md:ml-0 max-md:w-full">
                    <div className="relative my-auto box-border flex shrink-0 flex-col" />
                  </div>
                </div>
              </div>
            </section>
          </div>
          <div className="relative mt-5 box-border flex h-auto shrink-0 flex-col pb-8 pt-6">
            <div className="relative mt-5 box-border h-auto shrink-0 text-center text-3xl font-semibold text-emerald-400">
              <p>Une application 3-en-1</p>
            </div>
            <div className="relative mx-auto mt-5 box-border flex w-4/5 shrink-0 flex-col max-md:w-full">
              <div className="flex gap-5 max-sm:flex-col max-sm:gap-0">
                <div className="flex w-[33%] flex-col max-sm:ml-0 max-sm:w-full">
                  <img
                    loading="lazy"
                    sizes="(max-width: 998px) 26vw, 38vw"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=638 638w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=253 253w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Feed67f51951747a6b87e3ff72a6e2552?width=520 520w"
                    className="mt-5 box-border aspect-[3.53] min-h-[20px] w-full min-w-[20px] shrink-0 overflow-hidden object-contain"
                  />
                  <div className="relative mx-auto mt-5 box-border h-auto shrink-0 font-bold text-sky-400">
                    <p>Activités et communication</p>
                  </div>
                  <div className="relative mx-auto mt-2.5 h-auto w-[90%] shrink-0 text-center text-black max-md:text-sm">
                    <p>Envoi d'emails</p>
                    <p>Événements</p>
                    <p>Publications pour les réseaux sociaux</p>
                  </div>
                  <div className="relative mx-auto mt-2.5 h-auto shrink-0 text-center text-black underline max-sm:text-sm">
                    <p>Découvrir →</p>
                  </div>
                </div>
                <div className="ml-5 flex w-[33%] flex-col max-sm:ml-0 max-sm:w-full">
                  <img
                    loading="lazy"
                    sizes="(max-width: 998px) 26vw, 38vw"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=638 638w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=253 253w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2F75ba92adf9434ad3a99d021fbb232453?width=520 520w"
                    className="mt-5 box-border aspect-[3.53] min-h-[20px] w-full min-w-[20px] shrink-0 overflow-hidden object-contain"
                  />
                  <div className="relative mx-auto mt-5 box-border h-auto shrink-0 font-bold text-orange-400">
                    <p>Comptabilité</p>
                  </div>
                  <div className="relative mx-auto mt-2.5 h-auto w-[90%] shrink-0 text-center text-black max-md:text-sm">
                    <p>Paiement en ligne</p>
                    <p>Catalogue</p>
                    <p>Facturation</p>
                    <p>Bilan comptable</p>
                  </div>
                  <div className="relative mx-auto mt-2.5 h-auto shrink-0 text-center text-black underline max-sm:text-sm">
                    <p>
                      <span className="bg-[hsl(var(--background))]">
                        Découvrir
                      </span>
                      &nbsp;→
                    </p>
                  </div>
                </div>
                <div className="ml-5 flex w-[33%] flex-col max-sm:ml-0 max-sm:w-full">
                  <img
                    loading="lazy"
                    sizes="(max-width: 998px) 26vw, 38vw"
                    srcSet="https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=638 638w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=253 253w, https://cdn.builder.io/api/v1/image/assets%2F89d6bbb44070475d9580fd22f21ef8f1%2Ff8dab26c95d848afab3f277659749986?width=520 520w"
                    className="mt-5 box-border aspect-[3.53] min-h-[20px] w-full min-w-[20px] shrink-0 overflow-hidden object-contain"
                  />
                  <div className="relative mx-auto mt-5 box-border h-auto shrink-0 font-bold text-emerald-400">
                    <p>Adhésions</p>
                  </div>
                  <div className="relative mx-auto mt-2.5 h-auto w-[90%] shrink-0 text-center text-black max-md:text-sm">
                    <p>Cotisations</p>
                    <p>
                      Inscription et renouvellement
                      <br />
                      Email d'accueil
                    </p>
                    <p>Rappels automatique</p>
                  </div>
                  <div className="relative mx-auto mt-2.5 h-auto shrink-0 text-center text-black underline max-sm:text-sm">
                    <p>
                      <span className="bg-[hsl(var(--background))]">
                        Découvrir
                      </span>
                      &nbsp;→
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      <div className="builder-footer relative box-border flex min-h-[100px] shrink-0 flex-col bg-orange-400 px-5 py-8 text-white max-sm:pt-5">
        <section className="builder-footer relative mx-auto box-border flex min-h-[100px] w-full max-w-[1200px] shrink-0 grow flex-col self-stretch bg-orange-400 px-5 py-8 text-white max-sm:pt-5">
          <div className="relative mx-auto mt-5 box-border flex w-full max-w-[500px] shrink-0 flex-col">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex w-6/12 flex-col max-md:ml-0 max-md:w-full">
                <div className="relative box-border flex shrink-0 flex-col">
                  <div className="relative box-border flex shrink-0 flex-col">
                    <div className="relative box-border h-auto shrink-0 text-left text-base font-semibold text-white">
                      <p>Fonctionnalités</p>
                    </div>
                    <div className="relative box-border flex shrink-0 flex-col gap-2.5 pt-2.5 leading-relaxed">
                      <a
                        href="https://qwik.builder.io/docs/"
                        target="_blank"
                        className="pointer-events-auto relative box-border h-auto shrink-0 cursor-pointer text-left text-sm text-white"
                      >
                        <p>Activités et communication</p>
                      </a>
                      <a
                        href="https://qwik.builder.io/docs/qwikcity/"
                        target="_blank"
                        className="pointer-events-auto relative box-border h-auto shrink-0 cursor-pointer text-left text-sm text-white"
                      >
                        <p>Comptabilité</p>
                      </a>
                      <a
                        href="https://qwik.builder.io/docs/integrations/"
                        target="_blank"
                        className="pointer-events-auto relative box-border h-auto shrink-0 cursor-pointer text-left text-sm text-white"
                      >
                        <p>Adhésions</p>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className="ml-5 flex w-6/12 flex-col max-md:ml-0 max-md:w-full">
                <div className="relative box-border flex shrink-0 flex-col max-md:mt-7">
                  <div className="relative box-border h-auto shrink-0 text-left text-base font-semibold text-white">
                    <p>Wasso.org</p>
                  </div>
                  <div className="relative box-border flex shrink-0 flex-col gap-2.5 pt-2.5">
                    <a
                      href="https://www.builder.io/c/docs/how-builder-works"
                      target="_blank"
                      className="pointer-events-auto relative box-border h-auto shrink-0 cursor-pointer text-left text-sm text-white"
                    >
                      <p>Tarifs</p>
                    </a>
                    <a
                      href="https://www.builder.io/c/docs/custom-components-intro"
                      target="_blank"
                      className="pointer-events-auto relative box-border h-auto shrink-0 cursor-pointer text-left text-sm text-white"
                    >
                      <p>Contact</p>
                    </a>
                    <a
                      href="https://www.builder.io/c/blueprints"
                      target="_blank"
                      className="pointer-events-auto relative box-border h-auto shrink-0 cursor-pointer text-left text-sm text-white"
                    >
                      <p>Mentions légales</p>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
